######################  
# 1. Disable ILM & default template
######################
setup.ilm.enabled: false
setup.template.enabled: false

######################  
# 2. Inputs: use Filebeat’s newer filestream (not deprecated log)
######################
filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/auth-service/*.log
    # parse each line as JSON
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    # tag it so you can filter in ES if you want
    fields_under_root: true

processors:
  - decode_json_fields:
      fields: ["message"]       # The field that holds your nested JSON
      target: ""                # Merge decoded keys at the root level
      overwrite_keys: true      # Overwrite existing keys with decoded ones
      add_error_key: true       # Add an error key if decoding fails

  # Drop unnecessary metadata fields
  - drop_fields:
      fields: ["log", "input", "agent", "ecs", "host"]

######################  
# 3. Template registration for your custom index
######################
setup.template.name: "auth-service-logs"
setup.template.pattern: "auth-service-logs-*"
# You can point at your own template JSON if you have one:
# setup.template.file: "auth-service-template.json"

######################  
# 4. Ship straight into ES with your index name
######################
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "auth-service-logs-%{+yyyy.MM.dd}"

######################  
# 5. Filebeat’s own logs (optional)
######################
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644